### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by tisto** [kitconcept/volto-light-theme#1]
# Figma

https://www.figma.com/file/eYUCbivnNrnjXjBDUizSVX/Plone-6?node-id=64%3A7487&t=drxI24WYcv25UOEX-0

# Figma Export

![Frame 39](https://user-images.githubusercontent.com/632105/204846728-00546a7b-6d59-4bc0-b84e-17e87379d092.jpg)

**Comment by iRohitSingh** [comment]
Pr: https://github.com/kitconcept/bfs-intranet/pull/51
