### ISSUE TITLE
Hamburger menu and desktop menu are displayed at the same time

### ISSUE THREAD

**Issue by danalvrz** [kitconcept/volto-light-theme#18]
The mobile menu should be hidden if the screen is 980px width or more. This happens at 1090px instead. If the screen's width is anything in between, both menus will be displayed.

Screenshot: 
<img width="847" alt="screenshot" src="https://user-images.githubusercontent.com/89805481/208780399-ead776c4-fe00-44e2-9635-6df6c5a3023b.png">

**Comment by sneridagh** [comment]
In this theme (and in FZJ/DLR) we are changing the breakpoints (see the variables in: https://github.com/kitconcept/volto-light-theme/blob/main/src/theme/globals/site.variables#L42-L47) So could be that some segments are wrong or we don't want them like that. We have to check and adjust. We did that the previous projects, so you could check them out, or come up with new ones.

Check the behavior also in DLR as a template. I think we modified the tablet behavior, so it shows the hamburger quite soon for tablets (and small screens) too.

**Comment by danalvrz** [comment]
Fixed in: https://github.com/kitconcept/volto-light-theme/pull/16
