### ISSUE TITLE
Select problem in grid text block

### ISSUE THREAD

**Issue by iFlameing** [kitconcept/volto-light-theme#192]
screenshot @danalvrz @davisagli  you can clearly see my cursor is on second grid block text but editor showing the first one  selected.
![Screenshot 2023-08-02 at 6 25 29 PM](https://github.com/kitconcept/volto-light-theme/assets/33936987/b8ac352a-b922-4280-86fa-f3405fabfffa)
ot

**Comment by davisagli** [comment]
@iFlameing I updated volto in #195. Is it still an issue? If so, please explain the steps to reproduce and what you expected in more detail, because I'm not sure I understand the issue yet.

**Comment by iFlameing** [comment]
@davisagli Now it is fixed.
