### ISSUE TITLE
Image rights and add view is not working properly

### ISSUE THREAD

**Issue by iFlameing** [kitconcept/volto-light-theme#197]
@davisagli The image in add view doesn't have right size see the screenshot. Also adding in rights field should shown as copyright(This is fixed).

<img width="1280" alt="Screenshot 2023-08-10 at 8 00 45 PM" src="https://github.com/kitconcept/volto-light-theme/assets/33936987/31b9c12b-9e7b-44fc-806c-75bba7339d27">

**Comment by davisagli** [comment]
@iFlameing I need a better description of the problem. Steps to reproduce and what you are expecting

**Comment by sneridagh** [comment]
Fixed.
