### ISSUE TITLE
Content Page

### ISSUE THREAD

**Issue by tisto** [kitconcept/volto-light-theme#2]
# Figma

https://www.figma.com/file/eYUCbivnNrnjXjBDUizSVX/Plone-6?node-id=64%3A7751&t=drxI24WYcv25UOEX-0

# Figma Screenshot

![Frame 45](https://user-images.githubusercontent.com/632105/204847163-42965b67-0b7d-4814-9309-3ba3275399f2.png)

**Comment by iRohitSingh** [comment]
Pr: https://github.com/kitconcept/bfs-intranet/pull/51
