### ISSUE TITLE
Update default fallback image to match design

### ISSUE THREAD

**Issue by davisagli** [kitconcept/volto-light-theme#200]

**Comment by steffenri** [comment]
@davisagli Which block?

**Comment by davisagli** [comment]
@steffenri Sorry about the incomplete issue. This is about the listing block summary variation. Here is the design:

<img width="580" alt="Screenshot 2023-12-21 at 9 17 39 AM" src="https://github.com/kitconcept/volto-light-theme/assets/49014/baf32fbb-ce4b-46ef-9716-83be4cce568f">

The 2nd item is showing the fallback image.

I can't check if we did this, because there is a separate issue which is currently preventing any fallback image from being shown. https://github.com/plone/volto/issues/5379 -- for example, https://light-theme.kitconcept.io/block/listing-block should be showing fallback images under the "Summary" heading, I think.

**Comment by steffenri** [comment]
@davisagli You were right, there is a bug in vanilla volto that has to be fixed first, here's the PR: https://github.com/plone/volto/pull/5565

After this we can replace the fallback image.

**Comment by sneridagh** [comment]
merged, not backported to 17 yet though.

**Comment by iFlameing** [comment]
@davisagli @steffenri @sneridagh I checked the https://light-theme.kitconcept.io/block/listing-block Now there is preview image. If everything is working as expected then we should close this issue.

**Comment by davisagli** [comment]
Yep, looks like this works now, so I'll close it.
