### ISSUE TITLE
Sitemap is unstyled

### ISSUE THREAD

**Issue by fredvd** [kitconcept/volto-light-theme#209]
It doesn't need a major overhaul, but OOTB the title is positioned to close to the header and too small.

**Comment by fredvd** [comment]
<img width="1087" alt="Screenshot 2023-08-09 at 16 28 13" src="https://github.com/kitconcept/volto-light-theme/assets/394784/1548267e-f9d2-4374-9654-70389545367e">

**Comment by sneridagh** [comment]
@iRohitSingh ask ThomasB in gitlab if we need a mock for it.

**Comment by fredvd** [comment]
I'd like to reopen this issue. The sitemap has better styling now, but the left-right margins for the view are too wide IMHO. 
I assume this version of the sitemap is now live on light-theme.kitconcept.io @iRohitSingh 

Below I put the page content type demo above the sitemap view, the sitemap is wider than the normal page content, but also not as width as the first block on the homepage (teaser/carroussel), it floats somewhere in betweeen.  


<img width="1678" alt="Screenshot 2023-12-05 at 14 29 43" src="https://github.com/kitconcept/volto-light-theme/assets/394784/ffcb77d5-5242-4ed4-bf07-e524ca79c294">

<img width="1678" alt="Screenshot 2023-12-05 at 14 30 36" src="https://github.com/kitconcept/volto-light-theme/assets/394784/e55f70bf-e20c-49f5-abce-b369fde48d4c">

**Comment by fredvd** [comment]
@sneridagh Is there any general guidance on the width of layouts on content type views vs blockeditor views for light-theme?

**Comment by steffenri** [comment]
PR to fix h1 styling: https://github.com/kitconcept/volto-light-theme/pull/312

**Comment by steffenri** [comment]
Sitemap looks good now: https://light-theme.kitconcept.io/sitemap

![Sitemap](https://github.com/kitconcept/volto-light-theme/assets/54619639/9b56bda6-98d2-44d3-b449-d006c431cf64)


Closing..
