### ISSUE TITLE
Transfer `Image` component and `blurhash` to `@kitconcept/volto-image-block`

### ISSUE THREAD

**Issue by sneridagh** [kitconcept/volto-light-theme#21]
WIP: https://github.com/kitconcept/volto-image-block/pull/1

Tasks:

- [x] I'd like to change the name of the component and call it `Image`
- [ ] Proper storybook for the Image component
- [ ] Try to find edge cases (#22)
- [ ] Cypress tests for it covering common use cases and props usage for internal/external images
- [ ] Documentation outside the component (in Storybook is fine or in the repo README)

I'd like also to review in perspective the whole feature, since we have also:

https://github.com/kitconcept/dlr-internet/blob/a6db9c8931631efbcc0cba47bfba9ecc525f63db/frontend/src/addons/volto-dlr/src/helpers/PreviewImage/PreviewImage.js#L1

and I'd like to merge them both, if we think that the component interface should be improved.

/cc @davisagli @reekitconcept

**Comment by davisagli** [comment]
We updated volto-light-theme to use the core Image component instead. #177
