### ISSUE TITLE
[A11y] header has wrong tabbing order

### ISSUE THREAD

**Issue by ichim-david** [kitconcept/volto-light-theme#251]
Tab order on left to right language is expected to be done from left to right.

On https://light-theme.kitconcept.io/
Couple of issues:
- I would expect when tabbing around for first links to go to "Sitemap" and "Github"
followed by the Plone logo.
- I would expect to tab from the menu to the search icon and instead, I tab to the sitemap and github
- I shouldn't be able to tab to 9 since it's not something visible
- There is a jump between Sitemap, Search and Github when tabbing

Here is the tabbing order for the frontpage both logged in and auth, see from Firefox accessibility tab
![light-themefull-page-anon](https://github.com/kitconcept/volto-light-theme/assets/152852/33c1d755-2a8b-41e0-a32a-24b9ac49975b)
![light-themefull-page-auth](https://github.com/kitconcept/volto-light-theme/assets/152852/2c3aa735-c5ad-47b4-9619-ad17d3d97c65)

**Comment by sneridagh** [comment]
@iRohitSingh Status?

**Comment by iRohitSingh** [comment]
@sneridagh didn't get time to work on this.
