### ISSUE TITLE
Responsive breakpoints have gaps for navigation : desktop nav disappears without hamburger icon showing

### ISSUE THREAD

**Issue by fredvd** [kitconcept/volto-light-theme#265]
The current (fat menu?) implementation has gaps in the responsive width. Checked on https://light-theme.kitconcept.io

=> 1006px desktop navigation
977 - 1006  - no navigation at all
<= 977 - hamburger menu is shown

<img width="1003" alt="Screenshot 2023-11-19 at 16 42 43" src="https://github.com/kitconcept/volto-light-theme/assets/394784/81ded483-c5be-4a5e-a647-fdeae917df4a">

**Comment by sneridagh** [comment]
@iRohitSingh please check if they are ok now, I remember you working on this.
