### ISSUE TITLE
Light theme should use unitless values as oposed to static absolute values for line-height

### ISSUE THREAD

**Issue by ichim-david** [kitconcept/volto-light-theme#273]
https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#prefer_unitless_numbers_for_line-height_values

**Comment by sneridagh** [comment]
@danalvrz please take care of this. Make sure that the resultant values are still the same for all combinations.

**Comment by ichim-david** [comment]
default options will remain as it is, if someone uses VLT where the maps are used they can set new map values as decided in the pull request so closing this issue.
