### ISSUE TITLE
Navigation fails html validator due to use of divs inside ul tag

### ISSUE THREAD

**Issue by ichim-david** [kitconcept/volto-light-theme#289]
The screenshot is self explanatory
![navigation-validator](https://github.com/kitconcept/volto-light-theme/assets/152852/17fb2034-9e82-4de1-ad9b-090ed7f48b2e)

**Comment by tisto** [comment]
@ichim-david what kind of HTML validator did you run? Against what standard? Last time I checked there was no production-ready HTML validator around. Just the NU HTML validator, that is still in experimental mode:

https://validator.w3.org/nu/?doc=https%3A%2F%2Flight-theme.kitconcept.io%2F

With WHATWG and the "living standard" approach, validators became kind of useless. The validators section is "non normative":

https://html.spec.whatwg.org/#how-to-catch-mistakes-when-writing-html:-validators-and-conformance-checkers

I wouldn't put effort into those kinds of CS exercises tbh.

**Comment by ichim-david** [comment]
> @ichim-david what kind of HTML validator did you run? Against what standard? Last time I checked there was no production-ready HTML validator around. Just the NU HTML validator, that is still in experimental mode:
> 
> https://validator.w3.org/nu/?doc=https%3A%2F%2Flight-theme.kitconcept.io%2F
> 
> With WHATWG and the "living standard" approach, validators became kind of useless. The validators section is "non normative":
> 
> https://html.spec.whatwg.org/#how-to-catch-mistakes-when-writing-html:-validators-and-conformance-checkers
> 
> I wouldn't put effort into those kinds of CS exercises tbh.

@tisto yes as you can see from your link I was using the validator from w3.org

Maybe you would be right for some tags that are new and still subject to what would be correct but if we look at what is the permitted tags that should be inside an ul tag which is available from the start, you will see that having a div a a child of ul is breaking the spec
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul#technical_summary

This affects the accessibility of the list which Edge devtools complain about
![volto-light-theme-site](https://github.com/kitconcept/volto-light-theme/assets/152852/5a065d8d-f6f0-4253-808e-cb4bff1496df)
![edge-light-theme-devtools](https://github.com/kitconcept/volto-light-theme/assets/152852/57ccb006-c201-48bb-bd6e-c84a67c96a4c)
![a11y](https://github.com/kitconcept/volto-light-theme/assets/152852/5c38de99-9dd1-4d59-bac1-38e79e4703d1)

I know that most browsers are permissive and they allow HTML validation errors but that doesn't mean we shouldn't strive to write code that is valid which might not be read by other browsers otherwise.

**Comment by tisto** [comment]
@ichim-david ok, when it comes to accessibility we have to make sure that we pass all tests. The problem is that valid HTML is hard to test automatically. Basically because the testing infrastructure and the validators are in such a bad shape.

We have our a11y tests though, right @sneridagh?

Then I'd say we should fix those issues. Though, since we are touching the HTML structure, this is a breaking change.

**Comment by sneridagh** [comment]
@iRohitSingh now we have the a11y tests in place in VLT, so we can test this, right? please do, and fix accordingly.

**Comment by sneridagh** [comment]
@iRohitSingh status?

**Comment by iRohitSingh** [comment]
@sneridagh I am not able to understand the issue. Do I need to fix the html structure or I have to test the a11y for fat menu?

**Comment by sneridagh** [comment]
@iRohitSingh the only child a `<li>` supports is: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li#technical_summary

So `div` is not correct inside a `li`. Check if we have a proper a11y test for it (it should show). Then fix it.
