### ISSUE TITLE
When you disable the feature flag `enableFatMenu`, the mobile menu is gone too.

### ISSUE THREAD

**Issue by sneridagh** [kitconcept/volto-light-theme#297]
In mobile, it should stay always.

https://github.com/kitconcept/volto-light-theme#enable-fat-menu

**Comment by iRohitSingh** [comment]
@sneridagh I checked this out locally and works perfectly fine for me.
Please see the screencast for reference.

https://github.com/kitconcept/volto-light-theme/assets/61353484/3621d338-f021-4008-ba50-8f27b071febc

**Comment by sneridagh** [comment]
@iRohitSingh uh, ok, I will double check!

**Comment by sneridagh** [comment]
@iRohitSingh ok, I had an outdated shadow :( sorry about the noise.
