### ISSUE TITLE
Incorrect link in MobileNavigation component

### ISSUE THREAD

**Issue by ericof** [kitconcept/volto-light-theme#298]
The link to ```<FormattedMessage id="Home" defaultMessage="Home" />``` does not handle composite language codes like `pt-br`

**Comment by steffenri** [comment]
PR: https://github.com/kitconcept/volto-light-theme/pull/313

**Comment by steffenri** [comment]
PR merged.
Unfortunately no way to test this on https://light-theme.kitconcept.io/ because we are missing plone.app.multilingual but I checked it locally and it works.
Closing.
