### ISSUE TITLE
Search Animation

### ISSUE THREAD

**Issue by tisto** [kitconcept/volto-light-theme#3]
When the user clicks on the search icon in the site header, an animation is triggered that reveals a search field.

Ideas:

- https://github.com/tobiasahlin/animated-menu
- https://hematogenix.com/ https://twitter.com/RitikaAgrawal08/status/1566429244321763328?s=20&t=W-TZFjWYQDNbmMD8lnabZw (CodePen: https://codepen.io/RitikaAgrawal08/full/oNdgzep)
- https://swiftype.com/

**Comment by danalvrz** [comment]
Ready for review in our client project
