### ISSUE TITLE
Allow customizing the seconday navigation entries (Log in, Sitemap, GitHub)

### ISSUE THREAD

**Issue by tisto** [kitconcept/volto-light-theme#302]
To customize the secondary navigation entries, an integrator has to create a shadow copy of the header component. This might be a hard-to-overcome obstacle for non-JS-devs (think about an IT person who wants to give Plone a shot for their intranet) and it will also increase the technical depth for future upgrades (need to double-check on every upgrade).

Therefore we should allow customizing those secondary navigation entries. Either TTW (like Plone Classic in the old days via ZMI entries) or via a JSON configuration file.

I'd be open to both options. However, I would guess that a JSON configuration option is less work than full TTW capabilities.

# Screenshot

![Welcome-to-volto-light-theme](https://github.com/kitconcept/volto-light-theme/assets/632105/daafe568-8acf-4371-8b95-ad9dc8c94f24)

**Comment by tisto** [comment]
@sneridagh would you be ok with making the secondary navigation configurable via a JSON config? If you are ok with that @iFlameing could work on the implementation.

**Comment by tisto** [comment]
@robgietema just wondering about your opinion here. Do you have actions in your ZMI? :)

We would also need to check how this could work for multilingual sites...

**Comment by erral** [comment]
You can use Plone actions to achieve that (we already have an @actions endpoint in REST API, https://plonerestapi.readthedocs.io/en/latest/endpoints/actions.html) or use volto-dropdownmenu (https://github.com/collective/volto-dropdownmenu) for it.

**Comment by robgietema** [comment]
@tisto yes, nick also has actions: https://docs.nickcms.org/actions

**Comment by tisto** [comment]
@erral @robgietema thanks for the feedback. We will go with actions then. @iFlameing it would be awesome if you could give VLT a shot with a Nick backend as well for the feature we are developing here.

**Comment by sneridagh** [comment]
Fixed by: https://github.com/kitconcept/volto-light-theme/pull/320
