### ISSUE TITLE
Allow choosing between the internet and intranet header

### ISSUE THREAD

**Issue by tisto** [kitconcept/volto-light-theme#304]
We have two different header for VLT:

- default "internet" header (icon left, nav centered, search logo right) https://www.figma.com/file/eYUCbivnNrnjXjBDUizSVX/Volto-Light-Theme?type=design&node-id=994-8440&mode=design
- intranet header (icon left, search input field in the center, navigation below centered) https://www.figma.com/file/eYUCbivnNrnjXjBDUizSVX/Volto-Light-Theme?type=design&node-id=998-8774&mode=design

It should be possible to switch between the two headers via JSON configuration file.

# Internet Header

![header](https://github.com/kitconcept/volto-light-theme/assets/632105/688dfaa3-9dba-443a-a0a5-d7eb03f171e6)

# Intranet Header

![header (1)](https://github.com/kitconcept/volto-light-theme/assets/632105/9fd16648-aef8-44c6-822d-dd8c0b015c74)

**Comment by tisto** [comment]
@sneridagh I'd also like to being able to choose between the internet/intranet header in Volto light theme via a JSON config option. Are you ok with that? Then @iFlameing could work on an implementation.

**Comment by sneridagh** [comment]
Fixed by: https://github.com/kitconcept/volto-light-theme/pull/318

**Comment by sneridagh** [comment]
Merged!
