### ISSUE TITLE
Introduction Block: paragraph in edit mode is not reflected in view mode

### ISSUE THREAD

**Issue by iRohitSingh** [kitconcept/volto-light-theme#324]
https://github.com/kitconcept/volto-light-theme/assets/61353484/2beeac2c-4927-4442-81ac-23af23d62a60

**Comment by ankiiisharma** [comment]
Hey @iRohitSingh ,

I hope you're doing well. I'm very interested in working on this task and would appreciate it if you'd consider assigning it to me.

**Comment by davisagli** [comment]
@ankiiisharma There is already a fix in progress. If you'd like to help, you could test the fix in the linked PR and confirm whether it solves the problem.
