### ISSUE TITLE
Teaser Grid Block shows left/right margin when adding a new block

### ISSUE THREAD

**Issue by tisto** [kitconcept/volto-light-theme#354]
# StR

- as admin
- go to https://light-theme.kitconcept.io/add?type=Document
- add a new grid block with three columns
- choose "Teaser" subblock for the first column
- choose "Content Type" -> "Page" as a target
- -> Problem: teaser shows a big margin on the left/right side

# URL

https://light-theme.kitconcept.io/add?type=Document

# Screenshot

![Add-Document (6)](https://github.com/kitconcept/volto-light-theme/assets/632105/51f6735a-c26b-4c43-aa55-fdd32d4d778b)

**Comment by tisto** [comment]
@sneridagh this is blocking me from doing a screencast for my Plone Tagung keynote. Any chance you can have a look?

**Comment by sneridagh** [comment]
@tisto I am doing something wrong, but 

<img width="1628" alt="image" src="https://github.com/kitconcept/volto-light-theme/assets/486927/d89c42ac-20fd-46f6-8c70-4df5841dd717">

I can see it fine.

**Comment by sneridagh** [comment]
Same with the page you are trying...

<img width="1459" alt="image" src="https://github.com/kitconcept/volto-light-theme/assets/486927/09886c18-e7fd-4833-bd55-9faa23de9067">

**Comment by sneridagh** [comment]
and narrow:

<img width="1106" alt="image" src="https://github.com/kitconcept/volto-light-theme/assets/486927/6bbd3dc2-19e2-4ac8-ae53-b7325a0598e2">

**Comment by sneridagh** [comment]
We reviewed this a thousand times, by several people. Could be that we have a regression, at some point, for sure. But at least three or four pair of eyes are on this. 

Having the regression tool would help to automate tests for this, for sure. Luckily we will have it soon!

**Comment by sneridagh** [comment]
Ok, in a new page, in narrow windows, it is present. I will take a look but not today. Try a wider window, if possible.

**Comment by sneridagh** [comment]
More info, and it's the add page, the edit is unaffected! That's why in the home page it didn't show. :(

**Comment by tisto** [comment]
Yeah. Sorry if I did not make this clear. This only happens on the add view. However, I want to show how to create a new page from scratch. :(
