### ISSUE TITLE
Link in Introduction block is smaller than normal text

### ISSUE THREAD

**Issue by jonaspiterek** [kitconcept/volto-light-theme#365]
Link in Introduction block is smaller than normal text.
Link:
- `font-size: 18px`
- `line-height: 24px`

Text:
- `font-size: 24px`
- `line-height: 33px`

![image](https://github.com/kitconcept/volto-light-theme/assets/110389276/e7d1e21d-3476-4725-a754-623f8ae5fbc6)

**Comment by iRohitSingh** [comment]
pr : https://github.com/kitconcept/volto-light-theme/pull/366
