### ISSUE TITLE
There is no "start-frontend"

### ISSUE THREAD

**Issue by tisto** [kitconcept/volto-light-theme#5]
@sneridagh @ericof after running "make" I would have expected to have a "make start-frontend" command available. "yarn start" also did not work. What am I doing wrong here? :)

**Comment by sneridagh** [comment]
Since it's a bare add-on, it has no sense to have it without a project around. My proposal is that we make it easily doable via a Makefile command that calls `npx addon` command. Then guides the user to use the created vanilla project from there.

See #19
