### ISSUE TITLE
Backporting of listing customization from dlr.

### ISSUE THREAD

**Issue by iRohitSingh** [kitconcept/volto-light-theme#55]
See this issue which is opened in bfs-intranet.
 
 https://github.com/kitconcept/bfs-intranet/issues/46
 
 And these are files which is customised in dlr.
 
 https://github.com/kitconcept/dlr-internet/tree/main/frontend/src/addons/volto-dlr/src/customizations/volto/components/manage/Blocks/Listing

**Comment by iRohitSingh** [comment]
Pr: https://github.com/kitconcept/volto-light-theme/pull/42

**Comment by iFlameing** [comment]
@sneridagh checked this locally and it is fine. closing this issue.
