### ISSUE TITLE
Add style to Button block

### ISSUE THREAD

**Issue by iRohitSingh** [kitconcept/volto-light-theme#63]
https://www.figma.com/file/eYUCbivnNrnjXjBDUizSVX/Plone-6?node-id=385%3A5812&t=ckjGqMUdSZvV5AKV-0

**Comment by iRohitSingh** [comment]
Pr: https://github.com/kitconcept/volto-light-theme/pull/64

**Comment by iFlameing** [comment]
I checked it locally and works perfectly fine.

@sneridagh closing this issue since it is done.
